Add demonstration for error with @Principal injection
With logging level INFO all tests work, if logging level is changed to
FINE, tests fail with error:

java.lang.IllegalStateException: On a thread without an initialized
context nor a classloader mapping a deployed app